server:
  port: 9001
  shutdown: graceful
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      min-spare: 5
      max: 100

spring:
  application:
    name: Catalog service
  lifecycle:
    timeout-per-shutdown-phase: 15s
  data:
    mongodb:
      uri: mongodb://localhost:27017/product_catalog